import { MainEntity } from 'src/api/shared/entities/main.entity';
import { User } from 'src/api/users/entities/user.entity';
import { USER_ROLE } from 'src/api/users/types/user-roles.type';
import { Column, Entity, JoinColumn, ManyToOne, OneToOne } from 'typeorm';
import { Room } from './room.entity';

@Entity()
export class Message extends MainEntity {
  @Column()
  text: string;

  @Column({
    default: false,
  })
  isAutogenerated: boolean;

  @Column({
    default: false,
  })
  isInformative: boolean;

  @Column({
    type: 'enum',
    enum: USER_ROLE,
  })
  fromRole: USER_ROLE;

  @OneToOne(() => User)
  fromUser: User;

  @Column()
  roomId: string;

  @JoinColumn()
  @ManyToOne(() => Room, (room) => room.messages)
  room: Room;
}
